#!/usr/bin/env bun
// Installs the third-party skills listed in external/skills.json, unmodified, and keeps them out of Codex routing:
//   bun scripts/external-skills.ts --install [--home D]  npx skills add each source, then write the Codex hide block
//   bun scripts/external-skills.ts --check [--home D]    verify installs, accepted hashes, and the hide block, read-only
//   bun scripts/external-skills.ts --accept [--home D]   record the installed hashes in external/accepted.json after review
// `npx skills update -g` refreshes them later; --check then names every skill whose upstream content changed.
import { spawnSync } from "node:child_process"
import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

export type Source = { source: string; hidden: boolean; skills: string[] }

export function readManifest(repo: string): Source[] {
  const manifest = JSON.parse(readFileSync(join(repo, "external/skills.json"), "utf8")) as { sources?: Source[] }
  const sources = manifest.sources ?? []
  const names = sources.flatMap(source => source.skills)
  const duplicate = names.find((name, i) => names.indexOf(name) !== i)
  if (duplicate) throw new Error(`external/skills.json lists ${duplicate} twice`)
  const ours = new Set(existsSync(join(repo, "skills")) ? readdirSync(join(repo, "skills")) : [])
  const clash = names.find(name => ours.has(name))
  if (clash) throw new Error(`external/skills.json: ${clash} would replace this repo's own skill`)
  return sources
}

const begin = "# BEGIN codex-agents external skills (generated by scripts/external-skills.ts; do not edit)"
const end = "# END codex-agents external skills"

/** The Codex config block that hides each hidden skill from automatic routing; the files stay readable by path. */
export function codexHideBlock(sources: Source[], home: string): string {
  const entries = sources.filter(source => source.hidden).flatMap(source => source.skills).sort()
    .map(name => `[[skills.config]]\npath = ${JSON.stringify(join(home, ".agents/skills", name, "SKILL.md"))}\nenabled = false`)
  return [begin, ...entries, end].join("\n")
}

/** Replaces the managed block in a config, or appends it; everything else is kept byte for byte. */
export function withHideBlock(config: string, block: string): string {
  const start = config.indexOf(begin)
  if (start < 0) return `${config.replace(/\n*$/, "")}${config.trim() ? "\n\n" : ""}${block}\n`
  const stop = config.indexOf(end, start)
  if (stop < 0) throw new Error(`Codex config has "${begin}" without "${end}"; fix it by hand`)
  return config.slice(0, start) + block + config.slice(stop + end.length)
}

/** Where Codex reads its config and where the skills CLI keeps its lock; both follow the same env overrides as the tools. */
export type Paths = { home: string; codexHome: string; lockPath: string }
export function resolvePaths(home: string, env: Record<string, string | undefined> = process.env): Paths {
  return {
    home,
    codexHome: env.CODEX_HOME ? resolve(env.CODEX_HOME) : join(home, ".codex"),
    lockPath: env.XDG_STATE_HOME ? join(resolve(env.XDG_STATE_HOME), "skills/.skill-lock.json") : join(home, ".agents/.skill-lock.json"),
  }
}

export type Lock = { skills?: Record<string, { source?: string; skillFolderHash?: string }> }

/** The skills CLI lock, or an empty one. Errors name the file only. */
export function readLock(lockPath: string): Lock {
  if (!existsSync(lockPath)) return {}
  try {
    return JSON.parse(readFileSync(lockPath, "utf8"))
  } catch {
    throw new Error(`${lockPath} is not valid JSON; fix it and rerun (contents not shown)`)
  }
}

/** The config with the current hide block, refused when the result would not be valid TOML. */
export function nextConfig(configPath: string, sources: Source[], home: string): { config: string; next: string } {
  if (isLink(configPath) && !existsSync(configPath)) throw new Error(`${configPath} is a dangling symlink; fix or remove it, then rerun`)
  const config = existsSync(configPath) ? readFileSync(configPath, "utf8") : ""
  const next = withHideBlock(config, codexHideBlock(sources, home))
  try {
    Bun.TOML.parse(next)
  } catch {
    throw new Error(`the hide block would make ${configPath} invalid TOML, so nothing was installed; if the config already sets skills.config another way, move those entries into [[skills.config]] tables`)
  }
  return { config, next }
}

/** Writes a config through any symlink and keeps its permissions (0600 for a new file). */
export function writeConfig(configPath: string, next: string) {
  if (isLink(configPath) && !existsSync(configPath)) throw new Error(`${configPath} is a dangling symlink; fix or remove it, then rerun`)
  const target = existsSync(configPath) ? realpathSync(configPath) : configPath
  const mode = existsSync(target) ? statSync(target).mode & 0o777 : 0o600
  mkdirSync(dirname(target), { recursive: true })
  const temp = `${target}.tmp-${process.pid}`
  writeFileSync(temp, next, { mode })
  chmodSync(temp, mode)
  renameSync(temp, target)
}

function isLink(path: string) {
  try {
    return lstatSync(path).isSymbolicLink()
  } catch {
    return false
  }
}

type Options = { npx?: string; onLine?: (line: string) => void }

export function install(repo: string, paths: Paths, { npx = "npx", onLine = () => {} }: Options = {}) {
  const sources = readManifest(repo)
  // Settle the config edit before installing anything, so a config we cannot extend leaves no partial install.
  const configPath = join(paths.codexHome, "config.toml")
  const { config, next } = nextConfig(configPath, sources, paths.home)
  for (const { source, hidden, skills } of sources) {
    // Hidden skills go to the shared ~/.agents/skills root only, so Claude Code never lists them; our skills read them by path.
    const agents = hidden ? ["codex"] : ["codex", "claude-code"]
    const args = ["-y", "skills", "add", source, "--global", "--agent", ...agents, "--skill", ...skills, "--yes"]
    onLine(`$ ${npx} ${args.join(" ")}`)
    const result = spawnSync(npx, args, { stdio: "inherit", env: { ...process.env, HOME: paths.home } })
    if (result.status !== 0) throw new Error(`npx skills add ${source} failed with exit ${result.status}`)
  }
  if (next !== config) {
    writeConfig(configPath, next)
    onLine(`updated Codex hide block: ${configPath}`)
  }
}

/** Upstream folder hashes accepted for use, from external/accepted.json. */
export function readAccepted(repo: string): Record<string, string> {
  const path = join(repo, "external/accepted.json")
  return existsSync(path) ? (JSON.parse(readFileSync(path, "utf8")) as { skills?: Record<string, string> }).skills ?? {} : {}
}

/** Records the installed folder hash of every manifest skill as accepted. Run only after reviewing the upstream change. */
export function accept(repo: string, paths: Paths): string[] {
  const lock = readLock(paths.lockPath)
  const path = join(repo, "external/accepted.json")
  const doc = existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown> : {}
  const before = readAccepted(repo)
  const skills: Record<string, string> = {}
  for (const name of readManifest(repo).flatMap(source => source.skills).sort()) {
    const hash = lock.skills?.[name]?.skillFolderHash
    if (!hash) throw new Error(`${name} is not installed; run --install first`)
    skills[name] = hash
  }
  writeFileSync(path, JSON.stringify({ ...doc, skills }, null, 2) + "\n")
  return Object.keys(skills).filter(name => before[name] !== skills[name])
}

export function check(repo: string, paths: Paths): string[] {
  const sources = readManifest(repo)
  const problems: string[] = []
  const lock = readLock(paths.lockPath)
  const accepted = readAccepted(repo)
  for (const { source, skills } of sources) {
    for (const name of skills) {
      const entry = lock.skills?.[name]
      if (!entry) problems.push(`skill: ${name} is not installed (expected from ${source})`)
      else if (entry.source !== source) problems.push(`skill: ${name} comes from ${entry.source}, expected ${source}`)
      else if (!existsSync(join(paths.home, ".agents/skills", name, "SKILL.md"))) problems.push(`skill: ~/.agents/skills/${name}/SKILL.md is missing`)
      else if (!accepted[name] || entry.skillFolderHash !== accepted[name]) problems.push(`skill: ${name} differs from its accepted upstream version; review ~/.agents/skills/${name}, then run --accept`)
    }
  }
  const configPath = join(paths.codexHome, "config.toml")
  const config = existsSync(configPath) ? readFileSync(configPath, "utf8") : ""
  if (withHideBlock(config, codexHideBlock(sources, paths.home)) !== config) problems.push(`codex: ${configPath} lacks the current hide block; run --install`)
  return problems
}

function main(argv: string[]) {
  const repo = resolve(import.meta.dir, "..")
  const homeAt = argv.indexOf("--home")
  const mode = argv.find(arg => arg === "--install" || arg === "--check" || arg === "--accept")
  const home = homeAt >= 0 ? argv[homeAt + 1] : process.env.HOME
  if (!mode || !home) {
    console.error("usage: bun scripts/external-skills.ts --install|--check|--accept [--home DIR]")
    return 2
  }
  if (mode === "--install") {
    install(repo, resolvePaths(resolve(home)), { npx: process.env.EXTERNAL_SKILLS_NPX, onLine: line => console.log(line) })
    console.log("external skills installed")
    return 0
  }
  if (mode === "--accept") {
    const changed = accept(repo, resolvePaths(resolve(home)))
    console.log(changed.length ? `accepted new upstream versions: ${changed.join(", ")}` : "accepted versions unchanged")
    return 0
  }
  const problems = check(repo, resolvePaths(resolve(home)))
  for (const line of problems) console.error(line)
  if (problems.length) return 1
  console.log("external skills match external/skills.json")
  return 0
}

if (import.meta.main) {
  try {
    process.exit(main(process.argv.slice(2)))
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}
