import { describe, expect, test } from "bun:test"
import { chmodSync, cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { accept, check, readAccepted, codexHideBlock, install, readManifest, resolvePaths, withHideBlock, type Source } from "./external-skills.ts"

const repoRoot = join(import.meta.dir, "..")
const sources = [
  { source: "a/b", hidden: true, skills: ["zeta", "alpha"] },
  { source: "c/d", hidden: false, skills: ["shown"] },
]

describe("Codex hide block", () => {
  test("disables only hidden skills, by absolute SKILL.md path, sorted", () => {
    expect(codexHideBlock(sources, "/h")).toBe([
      "# BEGIN codex-agents external skills (generated by scripts/external-skills.ts; do not edit)",
      '[[skills.config]]\npath = "/h/.agents/skills/alpha/SKILL.md"\nenabled = false',
      '[[skills.config]]\npath = "/h/.agents/skills/zeta/SKILL.md"\nenabled = false',
      "# END codex-agents external skills",
    ].join("\n"))
  })

  test("appends once, replaces in place, keeps the rest of the config, and parses as TOML", () => {
    const config = 'model = "m"\n\n[agents]\nmax_depth = 2\n'
    const first = withHideBlock(config, codexHideBlock(sources, "/h"))
    expect(first.startsWith(config)).toBe(true)
    expect(withHideBlock(first, codexHideBlock(sources, "/h"))).toBe(first)
    const changed = withHideBlock(first + "[tail]\nx = 1\n", codexHideBlock([sources[1]!], "/h"))
    expect(changed).not.toContain("alpha")
    expect(changed).toEndWith("[tail]\nx = 1\n")
    const parsed = Bun.TOML.parse(first) as { skills: { config: { path: string; enabled: boolean }[] }; agents: { max_depth: number } }
    expect(parsed.skills.config.map(entry => entry.enabled)).toEqual([false, false])
    expect(parsed.agents.max_depth).toBe(2)
    expect(withHideBlock("", codexHideBlock([], "/h"))).toStartWith("# BEGIN")
    expect(() => withHideBlock("# BEGIN codex-agents external skills (generated by scripts/external-skills.ts; do not edit)\n", "x")).toThrow("without")
  })
})

// A temp root holding a repo with the given manifest and an empty home; removed after the body runs.
function withRoot(body: (paths: { root: string; repo: string; home: string }) => void, manifest: Source[] = sources) {
  const root = mkdtempSync(join(tmpdir(), "external-skills-"))
  try {
    const repo = join(root, "repo")
    mkdirSync(join(repo, "external"), { recursive: true })
    mkdirSync(join(repo, "skills"), { recursive: true })
    writeFileSync(join(repo, "external/skills.json"), JSON.stringify({ sources: manifest }))
    // Every fake skill's folder hash is `h-<name>`; the baseline accepts exactly those.
    const hashes = Object.fromEntries(manifest.flatMap(source => source.skills).map(name => [name, `h-${name}`]))
    writeFileSync(join(repo, "external/accepted.json"), JSON.stringify({ skills: hashes }))
    body({ root, repo, home: join(root, "home") })
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}

// Installs every manifest skill into home and records it in the lock the way npx skills would.
function installSkills(home: string, lockPath = join(home, ".agents/.skill-lock.json")) {
  const lock: Record<string, { source: string; skillFolderHash: string }> = {}
  for (const { source, skills } of sources) {
    for (const name of skills) {
      mkdirSync(join(home, ".agents/skills", name), { recursive: true })
      writeFileSync(join(home, ".agents/skills", name, "SKILL.md"), "x")
      lock[name] = { source, skillFolderHash: `h-${name}` }
    }
  }
  mkdirSync(join(lockPath, ".."), { recursive: true })
  writeFileSync(lockPath, JSON.stringify({ skills: lock }))
}

// `true` stands in for npx so install() only writes the Codex config.
const quietInstall = (repo: string, home: string, env: Record<string, string | undefined> = {}) => install(repo, resolvePaths(home, env), { npx: "true" })

describe("manifest", () => {
  test("the checked-in manifest lists each skill once and never shadows one of this repo's skills", () => {
    const names = readManifest(repoRoot).flatMap(source => source.skills)
    expect(names.length).toBeGreaterThan(30)
    expect(Object.keys(readAccepted(repoRoot)).sort()).toEqual([...names].sort())
    for (const hash of Object.values(readAccepted(repoRoot))) expect(hash).toMatch(/^[0-9a-f]{40}$/)
  })

  test("a skill listed twice, or one that shares a name with this repo's skills, is rejected", () => {
    withRoot(({ repo }) => {
      expect(() => readManifest(repo)).toThrow("alpha twice")
    }, [...sources, { source: "e/f", hidden: true, skills: ["alpha"] }])
    withRoot(({ repo }) => {
      mkdirSync(join(repo, "skills/shown"))
      expect(() => readManifest(repo)).toThrow("shown would replace this repo's own skill")
    })
  })
})

describe("paths", () => {
  test("CODEX_HOME and XDG_STATE_HOME move the Codex config and the skills lock", () => {
    expect(resolvePaths("/h", {})).toEqual({ home: "/h", codexHome: "/h/.codex", lockPath: "/h/.agents/.skill-lock.json" })
    expect(resolvePaths("/h", { CODEX_HOME: "/c", XDG_STATE_HOME: "/s" })).toEqual({ home: "/h", codexHome: "/c", lockPath: "/s/skills/.skill-lock.json" })
  })
})

describe("check", () => {
  test("reports a lock entry from another source and an absent lock", () => {
    withRoot(({ repo, home }) => {
      installSkills(home)
      quietInstall(repo, home)
      const paths = resolvePaths(home, {})
      expect(check(repo, paths)).toEqual([])
      const lock = JSON.parse(readFileSync(paths.lockPath, "utf8"))
      lock.skills.alpha.source = "evil/fork"
      writeFileSync(paths.lockPath, JSON.stringify(lock))
      expect(check(repo, paths)).toEqual(["skill: alpha comes from evil/fork, expected a/b"])
      rmSync(paths.lockPath)
      expect(check(repo, paths)).toEqual([
        "skill: zeta is not installed (expected from a/b)",
        "skill: alpha is not installed (expected from a/b)",
        "skill: shown is not installed (expected from c/d)",
      ])
    })
  })

  test("flags a skill whose upstream content changed or was never accepted, and --accept records the installed hashes", () => {
    withRoot(({ repo, home }) => {
      installSkills(home)
      quietInstall(repo, home)
      const paths = resolvePaths(home, {})
      const lock = JSON.parse(readFileSync(paths.lockPath, "utf8"))
      lock.skills.alpha.skillFolderHash = "h-alpha-v2"
      writeFileSync(paths.lockPath, JSON.stringify(lock))
      const drift = "skill: alpha differs from its accepted upstream version; review ~/.agents/skills/alpha, then run --accept"
      expect(check(repo, paths)).toEqual([drift])
      writeFileSync(join(repo, "external/accepted.json"), JSON.stringify({ reviewed: { "a/b": "abc" }, skills: {} }))
      expect(check(repo, paths)).toHaveLength(3)
      expect(accept(repo, paths)).toEqual(["alpha", "shown", "zeta"])
      expect(JSON.parse(readFileSync(join(repo, "external/accepted.json"), "utf8"))).toEqual({
        reviewed: { "a/b": "abc" },
        skills: { alpha: "h-alpha-v2", shown: "h-shown", zeta: "h-zeta" },
      })
      expect(check(repo, paths)).toEqual([])
      expect(accept(repo, paths)).toEqual([])
    })
  })

  test("reads the lock from XDG_STATE_HOME when set", () => {
    withRoot(({ root, repo, home }) => {
      installSkills(home, join(root, "state/skills/.skill-lock.json"))
      quietInstall(repo, home)
      expect(check(repo, resolvePaths(home, { XDG_STATE_HOME: join(root, "state") }))).toEqual([])
      expect(check(repo, resolvePaths(home, {}))).toContain("skill: alpha is not installed (expected from a/b)")
    })
  })
})

describe("Codex config writes", () => {
  test("keep an existing config's mode under umask 022 and create a new config as 0600", () => {
    const previous = process.umask(0o022)
    try {
      for (const mode of [0o600, 0o664]) {
        withRoot(({ repo, home }) => {
          const configPath = join(home, ".codex/config.toml")
          mkdirSync(join(home, ".codex"), { recursive: true })
          writeFileSync(configPath, 'model = "m"\n')
          chmodSync(configPath, mode)
          quietInstall(repo, home)
          expect(readFileSync(configPath, "utf8")).toContain("# BEGIN codex-agents")
          expect(statSync(configPath).mode & 0o777).toBe(mode)
        })
      }
      withRoot(({ repo, home }) => {
        quietInstall(repo, home)
        expect(statSync(join(home, ".codex/config.toml")).mode & 0o777).toBe(0o600)
      })
    } finally {
      process.umask(previous)
    }
  })

  test("write through a symlinked config and refuse a dangling one without writing", () => {
    withRoot(({ root, repo, home }) => {
      const link = join(home, ".codex/config.toml")
      const target = join(root, "dots/config.toml")
      mkdirSync(join(root, "dots"))
      mkdirSync(join(home, ".codex"), { recursive: true })
      writeFileSync(target, 'model = "m"\n')
      symlinkSync(target, link)
      quietInstall(repo, home)
      expect(lstatSync(link).isSymbolicLink()).toBe(true)
      expect(readFileSync(target, "utf8")).toStartWith('model = "m"\n\n# BEGIN codex-agents')
      expect(readdirSync(join(root, "dots"))).toEqual(["config.toml"])

      rmSync(target)
      const calls: string[] = []
      expect(() => install(repo, resolvePaths(home, {}), { npx: "true", onLine: line => calls.push(line) })).toThrow("dangling symlink")
      expect(calls).toEqual([])
      expect(existsSync(target)).toBe(false)
      expect(readdirSync(join(root, "dots"))).toEqual([])
      expect(readdirSync(join(home, ".codex"))).toEqual(["config.toml"])
      expect(lstatSync(link).isSymbolicLink()).toBe(true)
    })
  })

  test("refuse a config whose [skills] table already sets config, leaving it unchanged", () => {
    withRoot(({ repo, home }) => {
      const configPath = join(home, ".codex/config.toml")
      const original = 'model = "m"\n\n[skills]\nconfig = []\n'
      mkdirSync(join(home, ".codex"), { recursive: true })
      writeFileSync(configPath, original)
      const calls: string[] = []
      expect(() => install(repo, resolvePaths(home, {}), { npx: "true", onLine: line => calls.push(line) })).toThrow("invalid TOML")
      expect(calls).toEqual([])
      expect(readFileSync(configPath, "utf8")).toBe(original)
      expect(readdirSync(join(home, ".codex"))).toEqual(["config.toml"])
    })
  })
})

// A copy of the script in a temp repo plus a fake npx that records its arguments and installs each skill the way npx skills would.
function withScript(body: (paths: { root: string; repo: string; home: string; run: (env: Record<string, string>, ...args: string[]) => ReturnType<typeof Bun.spawnSync> }) => void) {
  withRoot(({ root, repo, home }) => {
    cpSync(join(repoRoot, "scripts/external-skills.ts"), join(repo, "scripts/external-skills.ts"))
    const npx = join(root, "npx")
    writeFileSync(npx, `#!/usr/bin/env bash
echo "$@" >> "${root}/calls"
src="$4"; while [ "$1" != --skill ]; do shift; done; shift
for name in "$@"; do [ "$name" = --yes ] && break; mkdir -p "$HOME/.agents/skills/$name"; echo x > "$HOME/.agents/skills/$name/SKILL.md"
  bun -e "const p='$HOME/.agents/.skill-lock.json';const f=Bun.file(p);const l=await f.exists()?await f.json():{skills:{}};l.skills['$name']={source:'$src',skillFolderHash:'h-$name'};await Bun.write(p,JSON.stringify(l))"; done
`)
    chmodSync(npx, 0o755)
    const run = (env: Record<string, string>, ...args: string[]) => {
      // The caller's CODEX_HOME and XDG_STATE_HOME must never reach the real config or lock.
      const base: Record<string, string | undefined> = { ...process.env, CODEX_HOME: undefined, XDG_STATE_HOME: undefined, EXTERNAL_SKILLS_NPX: npx, ...env }
      for (const key of Object.keys(base)) if (base[key] === undefined) delete base[key]
      return Bun.spawnSync({ cmd: ["bun", join(repo, "scripts/external-skills.ts"), ...args, "--home", home], env: base as Record<string, string>, stdout: "pipe", stderr: "pipe" })
    }
    body({ root, repo, home, run })
  })
}

describe("external-skills subprocess", () => {
  test("--install runs npx per source into the given home, writes the hide block, and --check verifies", () => {
    withScript(({ root, home, run }) => {
      mkdirSync(join(home, ".codex"), { recursive: true })
      writeFileSync(join(home, ".codex/config.toml"), 'model = "m"\n')
      expect(run({}, "--check").exitCode).toBe(1)
      const installed = run({}, "--install")
      expect(installed.exitCode).toBe(0)
      expect(readFileSync(join(root, "calls"), "utf8")).toBe(
        "-y skills add a/b --global --agent codex --skill zeta alpha --yes\n-y skills add c/d --global --agent codex claude-code --skill shown --yes\n")
      expect(readFileSync(join(home, ".codex/config.toml"), "utf8")).toStartWith('model = "m"\n\n# BEGIN')
      const checked = run({}, "--check")
      expect(checked.stderr.toString()).toBe("")
      expect(checked.exitCode).toBe(0)
      rmSync(join(home, ".agents/skills/alpha"), { recursive: true })
      expect(run({}, "--check").stderr.toString()).toContain("~/.agents/skills/alpha/SKILL.md is missing")
    })
  })

  test("--check fails on a stale or missing hide block and names the repair", () => {
    withScript(({ home, run }) => {
      expect(run({}, "--install").exitCode).toBe(0)
      const configPath = join(home, ".codex/config.toml")
      const diagnostic = `codex: ${configPath} lacks the current hide block; run --install\n`
      for (const config of [withHideBlock('model = "m"\n', codexHideBlock([sources[0]!, { ...sources[0]!, source: "x/y", skills: ["removed"] }], home)), 'model = "m"\n']) {
        writeFileSync(configPath, config)
        const checked = run({}, "--check")
        expect(checked.exitCode).toBe(1)
        expect(checked.stderr.toString()).toBe(diagnostic)
      }
    })
  })

  test("CODEX_HOME moves the config that --install writes and --check reads", () => {
    withScript(({ root, home, run }) => {
      const codexHome = join(root, "codex")
      expect(run({ CODEX_HOME: codexHome }, "--install").exitCode).toBe(0)
      expect(readFileSync(join(codexHome, "config.toml"), "utf8")).toContain("# BEGIN codex-agents")
      expect(existsSync(join(home, ".codex"))).toBe(false)
      expect(run({ CODEX_HOME: codexHome }, "--check").exitCode).toBe(0)
      const elsewhere = run({}, "--check")
      expect(elsewhere.exitCode).toBe(1)
      expect(elsewhere.stderr.toString()).toContain(`codex: ${join(home, ".codex/config.toml")} lacks the current hide block`)
    })
  })
})
